"""Kubernetes Deployment manifest generator."""

from __future__ import annotations

import yaml

from launchkit.core.config import LaunchKitConfig, ServiceConfig, ServiceType


def generate_deployment(name: str, service: ServiceConfig, cfg: LaunchKitConfig) -> str:
    """Generate a Kubernetes Deployment manifest."""
    registry = cfg.project.registry
    namespace = cfg.deploy.namespace
    project_name = cfg.project.name

    container: dict = {
        "name": name,
        "image": f"{registry}/{name}:latest",
        "imagePullPolicy": "Always",
    }

    # Port
    if service.type == ServiceType.WEB and service.port:
        container["ports"] = [{"containerPort": service.port}]

    # Resource requests/limits — use inferred profile or config values
    res = service.resources
    container["resources"] = {
        "requests": {"cpu": res.cpu_request, "memory": res.memory_request},
        "limits": {"cpu": res.cpu_limit, "memory": res.memory_limit},
    }

    # Health probes for web services
    if service.type == ServiceType.WEB and service.healthcheck and service.port:
        probe = {
            "httpGet": {
                "path": service.healthcheck,
                "port": service.port,
            },
            "initialDelaySeconds": 10,
            "periodSeconds": 15,
            "timeoutSeconds": 5,
            "failureThreshold": 3,
        }
        container["livenessProbe"] = probe
        container["readinessProbe"] = {
            **probe,
            "initialDelaySeconds": 5,
            "periodSeconds": 10,
        }

    # Environment variables from env_file hint
    if service.env_file:
        container["envFrom"] = [
            {"secretRef": {"name": f"{name}-env"}},
        ]

    manifest = {
        "apiVersion": "apps/v1",
        "kind": "Deployment",
        "metadata": {
            "name": name,
            "namespace": namespace,
            "labels": {
                "app": name,
                "project": project_name,
                "managed-by": "launchkit",
            },
        },
        "spec": {
            "replicas": service.scale.min,
            "selector": {
                "matchLabels": {"app": name},
            },
            "template": {
                "metadata": {
                    "labels": {
                        "app": name,
                        "project": project_name,
                    },
                },
                "spec": {
                    "containers": [container],
                },
            },
        },
    }

    # Add resource profile annotation so operators can see what was inferred
    if service.resources.profile:
        manifest["metadata"].setdefault("annotations", {})
        manifest["metadata"]["annotations"]["launchkit.dev/resource-profile"] = service.resources.profile

    header = (
        "# Generated by LaunchKit — https://github.com/SohamRupaye/launchkit\n"
        "# Do not edit manually — run `launchkit generate --only k8s` to regenerate\n"
    )
    return header + yaml.dump(manifest, default_flow_style=False, sort_keys=False)
