"""Kubernetes HorizontalPodAutoscaler manifest generator."""

from __future__ import annotations

import yaml

from launchkit.core.config import LaunchKitConfig, ServiceConfig


def generate_hpa(name: str, service: ServiceConfig, cfg: LaunchKitConfig) -> str:
    """Generate a Kubernetes HPA manifest from scale config."""
    namespace = cfg.deploy.namespace
    project_name = cfg.project.name
    scale = service.scale

    metrics: list[dict] = []

    # CPU metric
    metrics.append({
        "type": "Resource",
        "resource": {
            "name": "cpu",
            "target": {
                "type": "Utilization",
                "averageUtilization": scale.cpu_threshold,
            },
        },
    })

    # Memory metric (optional)
    if scale.memory_threshold is not None:
        metrics.append({
            "type": "Resource",
            "resource": {
                "name": "memory",
                "target": {
                    "type": "Utilization",
                    "averageUtilization": scale.memory_threshold,
                },
            },
        })

    manifest = {
        "apiVersion": "autoscaling/v2",
        "kind": "HorizontalPodAutoscaler",
        "metadata": {
            "name": f"{name}-hpa",
            "namespace": namespace,
            "labels": {
                "app": name,
                "project": project_name,
                "managed-by": "launchkit",
            },
        },
        "spec": {
            "scaleTargetRef": {
                "apiVersion": "apps/v1",
                "kind": "Deployment",
                "name": name,
            },
            "minReplicas": scale.min,
            "maxReplicas": scale.max,
            "metrics": metrics,
        },
    }

    header = (
        "# Generated by LaunchKit — https://github.com/SohamRupaye/launchkit\n"
        "# Do not edit manually — run `launchkit generate --only k8s` to regenerate\n"
    )
    return header + yaml.dump(manifest, default_flow_style=False, sort_keys=False)
