"""Kubernetes Ingress manifest generator."""

from __future__ import annotations

import yaml

from launchkit.core.config import LaunchKitConfig, ServiceType


def generate_ingress(cfg: LaunchKitConfig) -> str:
    """Generate a Kubernetes Ingress manifest."""
    namespace = cfg.deploy.namespace
    project_name = cfg.project.name
    ingress_cfg = cfg.deploy.ingress
    host = ingress_cfg.host or f"{project_name}.example.com"

    # Build rules: one path per web service with a port
    paths: list[dict] = []
    for name, service in cfg.services.items():
        if service.type == ServiceType.WEB and service.port:
            paths.append({
                "path": f"/{name}",
                "pathType": "Prefix",
                "backend": {
                    "service": {
                        "name": name,
                        "port": {"number": 80},
                    },
                },
            })

    # If only one web service, use root path
    if len(paths) == 1:
        paths[0]["path"] = "/"

    manifest: dict = {
        "apiVersion": "networking.k8s.io/v1",
        "kind": "Ingress",
        "metadata": {
            "name": f"{project_name}-ingress",
            "namespace": namespace,
            "labels": {
                "project": project_name,
                "managed-by": "launchkit",
            },
            "annotations": {},
        },
        "spec": {
            "rules": [
                {
                    "host": host,
                    "http": {"paths": paths},
                },
            ],
        },
    }

    # TLS with cert-manager
    if ingress_cfg.tls:
        manifest["metadata"]["annotations"]["cert-manager.io/cluster-issuer"] = "letsencrypt-prod"
        manifest["spec"]["tls"] = [
            {
                "hosts": [host],
                "secretName": f"{project_name}-tls",
            },
        ]

    # Clean up empty annotations
    if not manifest["metadata"]["annotations"]:
        del manifest["metadata"]["annotations"]

    header = (
        "# Generated by LaunchKit — https://github.com/SohamRupaye/launchkit\n"
        "# Do not edit manually — run `launchkit generate --only k8s` to regenerate\n"
    )
    return header + yaml.dump(manifest, default_flow_style=False, sort_keys=False)
