"""Kubernetes Service manifest generator."""

from __future__ import annotations

import yaml

from launchkit.core.config import LaunchKitConfig, ServiceConfig


def generate_service(name: str, service: ServiceConfig, cfg: LaunchKitConfig) -> str:
    """Generate a Kubernetes Service manifest (ClusterIP)."""
    namespace = cfg.deploy.namespace
    project_name = cfg.project.name
    port = service.port or 80

    manifest = {
        "apiVersion": "v1",
        "kind": "Service",
        "metadata": {
            "name": name,
            "namespace": namespace,
            "labels": {
                "app": name,
                "project": project_name,
                "managed-by": "launchkit",
            },
        },
        "spec": {
            "type": "ClusterIP",
            "selector": {"app": name},
            "ports": [
                {
                    "name": "http",
                    "port": 80,
                    "targetPort": port,
                    "protocol": "TCP",
                },
            ],
        },
    }

    header = (
        "# Generated by LaunchKit — https://github.com/SohamRupaye/launchkit\n"
        "# Do not edit manually — run `launchkit generate --only k8s` to regenerate\n"
    )
    return header + yaml.dump(manifest, default_flow_style=False, sort_keys=False)
