"""Nginx reverse proxy generator — generates nginx.conf and K8s/Compose resources."""

from __future__ import annotations

import yaml

from launchkit.core.config import LaunchKitConfig, ServiceType
from launchkit.utils.templates import render_template


def generate_nginx_conf(cfg: LaunchKitConfig) -> str:
    """Generate an nginx.conf for reverse-proxying web services."""
    web_services = {
        name: svc for name, svc in cfg.services.items()
        if svc.type == ServiceType.WEB and svc.port
    }

    if not web_services:
        return ""

    nginx = cfg.deploy.nginx
    host = cfg.deploy.ingress.host or "localhost"

    return render_template(
        "nginx/nginx.conf.j2",
        web_services=web_services,
        server_name=host,
        tls=cfg.deploy.ingress.tls,
        rate_limit=nginx.rate_limit,
        client_max_body=nginx.client_max_body,
        gzip=nginx.gzip,
        project_name=cfg.project.name,
    )


def generate_nginx_k8s(cfg: LaunchKitConfig) -> str:
    """Generate K8s Deployment + Service + ConfigMap for nginx."""
    namespace = cfg.deploy.namespace
    project_name = cfg.project.name

    configmap = {
        "apiVersion": "v1",
        "kind": "ConfigMap",
        "metadata": {
            "name": f"{project_name}-nginx-config",
            "namespace": namespace,
            "labels": {
                "app": f"{project_name}-nginx",
                "managed-by": "launchkit",
            },
        },
        "data": {
            "nginx.conf": "# Mount generated nginx.conf here\n# See nginx/nginx.conf in your project root\n",
        },
    }

    deployment = {
        "apiVersion": "apps/v1",
        "kind": "Deployment",
        "metadata": {
            "name": f"{project_name}-nginx",
            "namespace": namespace,
            "labels": {
                "app": f"{project_name}-nginx",
                "project": project_name,
                "managed-by": "launchkit",
            },
        },
        "spec": {
            "replicas": 2,
            "selector": {"matchLabels": {"app": f"{project_name}-nginx"}},
            "template": {
                "metadata": {
                    "labels": {
                        "app": f"{project_name}-nginx",
                        "project": project_name,
                    },
                },
                "spec": {
                    "containers": [{
                        "name": "nginx",
                        "image": "nginx:1.27-alpine",
                        "ports": [
                            {"containerPort": 80},
                            {"containerPort": 443},
                        ],
                        "volumeMounts": [{
                            "name": "nginx-config",
                            "mountPath": "/etc/nginx/nginx.conf",
                            "subPath": "nginx.conf",
                        }],
                        "resources": {
                            "requests": {"cpu": "50m", "memory": "64Mi"},
                            "limits": {"cpu": "200m", "memory": "128Mi"},
                        },
                        "livenessProbe": {
                            "httpGet": {"path": "/nginx-health", "port": 80},
                            "initialDelaySeconds": 5,
                            "periodSeconds": 10,
                        },
                        "readinessProbe": {
                            "httpGet": {"path": "/nginx-health", "port": 80},
                            "initialDelaySeconds": 3,
                            "periodSeconds": 5,
                        },
                    }],
                    "volumes": [{
                        "name": "nginx-config",
                        "configMap": {"name": f"{project_name}-nginx-config"},
                    }],
                },
            },
        },
    }

    service = {
        "apiVersion": "v1",
        "kind": "Service",
        "metadata": {
            "name": f"{project_name}-nginx",
            "namespace": namespace,
            "labels": {
                "app": f"{project_name}-nginx",
                "managed-by": "launchkit",
            },
        },
        "spec": {
            "type": "LoadBalancer",
            "ports": [
                {"name": "http", "port": 80, "targetPort": 80},
                {"name": "https", "port": 443, "targetPort": 443},
            ],
            "selector": {"app": f"{project_name}-nginx"},
        },
    }

    header = (
        "# Generated by LaunchKit — https://github.com/SohamRupaye/launchkit\n"
        "# Nginx reverse proxy — Deployment + Service + ConfigMap\n"
        "---\n"
    )

    docs = [
        yaml.dump(configmap, default_flow_style=False, sort_keys=False),
        yaml.dump(deployment, default_flow_style=False, sort_keys=False),
        yaml.dump(service, default_flow_style=False, sort_keys=False),
    ]

    return header + "---\n".join(docs)
