"""Eject — remove LaunchKit markers and leave clean standalone files."""

from __future__ import annotations

import re
from pathlib import Path

from rich.console import Console

from launchkit.utils.printer import print_header, print_info, print_success, print_warning


# Patterns to strip from generated files
HEADER_PATTERNS = [
    re.compile(r"^# Generated by LaunchKit.*\n", re.MULTILINE),
    re.compile(r"^# Do not edit manually.*\n", re.MULTILINE),
]

YAML_LABEL_PATTERNS = [
    re.compile(r"^\s*managed-by:\s*launchkit\s*\n", re.MULTILINE),
]

YAML_ANNOTATION_PATTERNS = [
    re.compile(r"^\s*launchkit\.dev/[\w-]+:.*\n", re.MULTILINE),
]


def run_eject(root: str, yes: bool, console: Console) -> None:
    """
    Remove LaunchKit markers from all generated files and delete launchkit.yaml.

    After eject, the files are standalone and LaunchKit-free.
    """
    project = Path(root).resolve()
    config_path = project / "launchkit.yaml"

    if not config_path.exists():
        print_warning(console, "No launchkit.yaml found — nothing to eject.")
        return

    print_header(console, "LaunchKit Eject")
    print_info(console, "This will remove all LaunchKit markers and delete launchkit.yaml.")
    print_info(console, "Your generated files will remain as clean, standalone files.")

    # Discover managed files
    managed_files = _find_managed_files(project)

    if not managed_files:
        print_info(console, "No managed files found.")
    else:
        console.print()
        for f in managed_files:
            rel = str(f.relative_to(project))
            console.print(f"  [dim]→[/dim] {rel}")

    console.print()

    if not yes:
        confirm = console.input("[bold]Eject and remove LaunchKit markers? [y/N][/bold] ")
        if confirm.lower() not in ("y", "yes"):
            print_info(console, "Aborted.")
            return

    # Strip markers from all managed files
    cleaned = 0
    for filepath in managed_files:
        if _clean_file(filepath):
            cleaned += 1

    # Delete launchkit.yaml
    config_path.unlink()

    # Also delete launchkit.yaml.example if it exists
    example = project / "launchkit.yaml.example"
    if example.exists():
        example.unlink()

    console.print()
    print_success(
        console,
        f"Ejected! Cleaned {cleaned} file(s), deleted launchkit.yaml.",
    )
    print_info(console, "Your files are now standalone — LaunchKit is no longer tracking them.")


def _find_managed_files(root: Path) -> list[Path]:
    """Find all files that contain LaunchKit markers."""
    managed: list[Path] = []

    # Check common generated paths
    candidates = list(root.rglob("Dockerfile"))
    candidates += list(root.rglob("docker-compose.yml"))
    candidates += list(root.rglob("*.yaml"))
    candidates += list(root.rglob("*.yml"))
    candidates += list(root.rglob("nginx.conf"))

    for f in candidates:
        if not f.is_file():
            continue
        # Skip launchkit.yaml itself
        if f.name == "launchkit.yaml" or f.name == "launchkit.yaml.example":
            continue
        # Skip hidden/vendor dirs
        parts = f.relative_to(root).parts
        if any(p.startswith(".") and p != ".github" for p in parts):
            continue
        if "node_modules" in parts or ".venv" in parts:
            continue

        try:
            content = f.read_text()
            if "Generated by LaunchKit" in content or "managed-by: launchkit" in content:
                managed.append(f)
        except (OSError, UnicodeDecodeError):
            continue

    return sorted(managed)


def _clean_file(filepath: Path) -> bool:
    """Remove LaunchKit markers from a single file. Returns True if modified."""
    try:
        original = filepath.read_text()
    except (OSError, UnicodeDecodeError):
        return False

    content = original

    # Strip header comments
    for pattern in HEADER_PATTERNS:
        content = pattern.sub("", content)

    # Strip managed-by labels
    for pattern in YAML_LABEL_PATTERNS:
        content = pattern.sub("", content)

    # Strip launchkit annotations
    for pattern in YAML_ANNOTATION_PATTERNS:
        content = pattern.sub("", content)

    # Clean up empty annotations: block if it's now empty
    content = re.sub(r"^\s*annotations:\s*\n(?=\s*\w)", "", content, flags=re.MULTILINE)

    # Remove leading blank lines
    content = content.lstrip("\n")

    if content != original:
        filepath.write_text(content)
        return True
    return False
