"""Core engine — orchestrates the detect → generate pipeline."""

from __future__ import annotations

from pathlib import Path

import yaml
from rich.console import Console

from launchkit.core.config import (
    CIProvider,
    DeployTarget,
    LaunchKitConfig,
    ServiceConfig,
    ServiceType,
    apply_environment,
    load_and_validate,
)
from launchkit.detectors.base import DetectedService, detect_services
from launchkit.detectors.environment import detect_environment
from launchkit.detectors.resources import infer_resource_profile
from launchkit.generators.ci.github import generate_github_actions
from launchkit.generators.ci.gitlab import generate_gitlab_ci
from launchkit.generators.compose import generate_compose
from launchkit.generators.docker.dotnet import generate_dotnet_dockerfile
from launchkit.generators.docker.go import generate_go_dockerfile
from launchkit.generators.docker.java import generate_java_dockerfile
from launchkit.generators.docker.node import generate_node_dockerfile
from launchkit.generators.docker.php import generate_php_dockerfile
from launchkit.generators.docker.python import generate_python_dockerfile
from launchkit.generators.docker.ruby import generate_ruby_dockerfile
from launchkit.generators.docker.rust import generate_rust_dockerfile
from launchkit.generators.kubernetes.deployment import generate_deployment
from launchkit.generators.kubernetes.hpa import generate_hpa
from launchkit.generators.kubernetes.ingress import generate_ingress
from launchkit.generators.kubernetes.secrets import generate_secrets_hint
from launchkit.generators.kubernetes.service import generate_service
from launchkit.generators.nginx import generate_nginx_conf, generate_nginx_k8s
from launchkit.utils.fs import safe_write
from launchkit.utils.printer import (
    print_detected_services,
    print_error,
    print_generated,
    print_header,
    print_info,
    print_skipped,
    print_success,
    print_summary_table,
    print_warning,
)


# ── Init Engine ──────────────────────────────────────────────────────────────


class InitEngine:
    """Scans a project directory, detects services, and scaffolds launchkit.yaml."""

    def __init__(self, root: str, force: bool, console: Console, target: str = "auto") -> None:
        self.root = Path(root).resolve()
        self.force = force
        self.console = console
        self.target = target

    def run(self) -> None:
        config_path = self.root / "launchkit.yaml"

        if config_path.exists() and not self.force:
            print_warning(
                self.console,
                "launchkit.yaml already exists. Use --force to overwrite.",
            )
            return

        print_header(self.console, "Detecting your stack")
        services = detect_services(self.root)

        if not services:
            print_error(
                self.console,
                "No services detected. Make sure your project has a "
                "requirements.txt, package.json, or go.mod.",
            )
            return

        # Detect environment context
        print_header(self.console, "Analyzing project environment")
        env = detect_environment(self.root)

        # Display detected services
        svc_dicts = [
            {
                "name": s.name,
                "lang": s.lang,
                "framework": s.framework or "—",
                "port": str(s.port) if s.port else "—",
                "type": s.service_type,
            }
            for s in services
        ]
        print_detected_services(self.console, svc_dicts)

        # Show inferred environment
        print_info(self.console, f"CI provider: [bold]{env.ci_provider}[/bold] (auto-detected)")
        print_info(self.console, f"Default branch: [bold]{env.default_branch}[/bold]")
        if len(env.branches) > 1:
            print_info(self.console, f"Branch strategy: [bold]{', '.join(env.branches)}[/bold]")
        if env.registry_hint:
            print_info(self.console, f"Registry: [bold]{env.registry_hint}[/bold] (from git remote)")

        # Build YAML with inferred intelligence
        config_dict = self._build_config(services, env)
        yaml_content = yaml.dump(config_dict, default_flow_style=False, sort_keys=False)

        output = (
            "# LaunchKit config — generated by `launchkit init`\n"
            "# Edit this file, then run `launchkit generate`\n"
            "# Full reference: docs/config-reference.md\n\n"
            + yaml_content
        )

        config_path.write_text(output)
        print_success(self.console, f"Generated {config_path.relative_to(self.root)}")
        print_info(self.console, "Next: review launchkit.yaml, then run `launchkit generate`")

    def _build_config(self, services: list[DetectedService], env: object) -> dict:
        from launchkit.detectors.environment import EnvironmentContext

        ctx: EnvironmentContext = env  # type: ignore
        project_name = self.root.name.lower().replace(" ", "-")
        registry = ctx.registry_hint or f"ghcr.io/yourname/{project_name}"

        # Clamp the detected CI provider to one the config schema supports.
        # `detect_ci_provider` can return jenkins/circleci/travis/azure, but only
        # github/gitlab/bitbucket generate — writing an unsupported value here would
        # make the very next `generate` fail schema validation.
        detected_provider = ctx.ci_provider
        supported_providers = {p.value for p in CIProvider}
        if detected_provider not in supported_providers:
            print_warning(
                self.console,
                f"Detected CI provider '{detected_provider}' is not yet supported — "
                f"defaulting to 'github'. Change `ci.provider` in launchkit.yaml if needed.",
            )
            ci_provider = "github"
        else:
            ci_provider = detected_provider

        svc_dict: dict = {}
        for s in services:
            service_path = self.root / s.path if s.path != "." else self.root
            profile = infer_resource_profile(
                lang=s.lang,
                framework=s.framework,
                service_type=s.service_type,
                service_path=service_path,
            )

            entry: dict = {"lang": s.lang}
            if s.framework:
                entry["framework"] = s.framework
            if s.port:
                entry["port"] = s.port
            if s.service_type == "worker":
                entry["type"] = "worker"
            if s.command:
                entry["command"] = s.command
            if s.service_type == "web":
                entry["healthcheck"] = "/health"

            entry["resources"] = {
                "profile": profile.profile_name,
                "cpu_request": profile.cpu_request,
                "cpu_limit": profile.cpu_limit,
                "memory_request": profile.memory_request,
                "memory_limit": profile.memory_limit,
            }
            entry["scale"] = {
                "min": profile.scale_min,
                "max": profile.scale_max,
                "cpu_threshold": profile.cpu_threshold,
            }
            if profile.memory_threshold:
                entry["scale"]["memory_threshold"] = profile.memory_threshold

            svc_dict[s.name] = entry

        # `verify` gates the build/push on LaunchKit proving the generated output.
        if ctx.has_tests:
            steps = ["lint", "test", "verify", "build", "push"]
        else:
            steps = ["verify", "build", "push"]

        # Infer target infra
        deploy_target = self.target
        if deploy_target == "auto":
            deploy_target = "compose" if len(services) <= 4 else "kubernetes"
            auto_msg = "[dim]autoscaled to monorepo K8s[/dim]" if deploy_target == "kubernetes" else "[dim]autoscaled to simple compose[/dim]"
            print_info(self.console, f"Deploy target: [bold]{deploy_target}[/bold] {auto_msg}")

        return {
            "version": "1",
            "project": {
                "name": project_name,
                "registry": registry,
            },
            "services": svc_dict,
            "infrastructure": {},
            "environments": {
                "staging": {
                    "namespace": "staging",
                    "domain": f"staging.{project_name}.dev",
                    "scale": {"max": 2},
                },
                "production": {
                    "namespace": "production",
                    "domain": f"{project_name}.dev",
                    "tls": True,
                    "scale": {"max": 10},
                    "replicas": 2,
                },
            },
            "ci": {
                "provider": ci_provider,
                "affected_only": len(services) > 1,
                "branches": ctx.branches,
                "steps": steps,
            },
            "deploy": {
                "target": deploy_target,
                "namespace": "production",
            },
        }


# ── Generate Engine ──────────────────────────────────────────────────────────


class GenerateEngine:
    """Loads config and dispatches to Docker/CI/K8s/Compose/Nginx generators."""

    def __init__(
        self,
        config_path: str,
        only: str | None,
        dry_run: bool,
        console: Console,
        env: str | None = None,
    ) -> None:
        self.config_path = config_path
        self.only = only
        self.dry_run = dry_run
        self.console = console
        self.env = env

    def run(self) -> None:
        try:
            cfg = load_and_validate(self.config_path)
        except FileNotFoundError as e:
            print_error(self.console, str(e))
            raise SystemExit(1)
        except Exception as e:
            print_error(self.console, f"Config validation failed: {e}")
            raise SystemExit(1)

        # Apply environment overrides if specified
        if self.env:
            try:
                cfg = apply_environment(cfg, self.env)
                print_info(
                    self.console,
                    f"Using environment: [bold]{self.env}[/bold] "
                    f"(namespace: {cfg.deploy.namespace})",
                )
            except ValueError as e:
                print_error(self.console, str(e))
                raise SystemExit(1)

        # Honor any project-local template overrides (.launchkit/templates/).
        from launchkit.utils.templates import set_template_override
        set_template_override(Path(self.config_path).resolve().parent)

        num_services = len(cfg.services)
        print_info(
            self.console,
            f"Detected {'monorepo' if num_services > 1 else 'project'} "
            f"with {num_services} service(s)",
        )

        results: list[tuple[str, str]] = []

        # Output root: k8s/<env>/ when using --env, else project root
        output_root = Path(self.config_path).resolve().parent
        k8s_prefix = f"k8s/{self.env}" if self.env else "k8s"

        if self.only is None or self.only == "docker":
            results += self._generate_dockerfiles(cfg, output_root)

        if self.only is None or self.only == "compose":
            results += self._generate_compose(cfg, output_root)

        if self.only is None or self.only == "ci":
            results += self._generate_ci(cfg, output_root)

        if self.only is None or self.only == "k8s":
            results += self._generate_k8s(cfg, output_root, k8s_prefix)

        if self.only is None or self.only == "nginx":
            results += self._generate_nginx(cfg, output_root, k8s_prefix)

        # Summary
        print_summary_table(self.console, results)

        generated = sum(1 for _, s in results if s in ("generated", "dry-run"))
        status = "dry-run" if self.dry_run else "generated"
        self.console.print(
            f"\n[bold]{generated} file(s) {status}.[/bold] "
            f"Run `launchkit diff` to see what changed."
        )

    def _generate_dockerfiles(
        self, cfg: LaunchKitConfig, root: Path
    ) -> list[tuple[str, str]]:
        results: list[tuple[str, str]] = []

        for name, service in cfg.services.items():
            if len(cfg.services) > 1:
                filepath = root / "services" / name / "Dockerfile"
            else:
                filepath = root / "Dockerfile"

            if filepath.exists() and not self.dry_run:
                rel = str(filepath.relative_to(root))
                print_skipped(self.console, rel, reason="already exists")
                results.append((rel, "skipped"))
                continue

            dockerfile = _build_dockerfile(name, service, filepath.parent)
            rel = str(filepath.relative_to(root))
            wrote = safe_write(filepath, dockerfile, dry_run=self.dry_run)
            status = ("dry-run" if self.dry_run else "generated") if wrote else "skipped"
            if wrote:
                print_generated(self.console, rel)
            else:
                print_skipped(self.console, rel)
            results.append((rel, status))

        return results

    def _generate_compose(
        self, cfg: LaunchKitConfig, root: Path
    ) -> list[tuple[str, str]]:
        target = cfg.deploy.target
        if target not in (DeployTarget.COMPOSE, DeployTarget.BOTH):
            if self.only == "compose":
                print_info(self.console, "deploy.target is not 'compose' or 'both' — generating anyway")
            elif self.only is None:
                return []

        content = generate_compose(cfg)
        filepath = root / "docker-compose.yml"
        rel = str(filepath.relative_to(root))
        wrote = safe_write(filepath, content, dry_run=self.dry_run)
        status = ("dry-run" if self.dry_run else "generated") if wrote else "skipped"
        if wrote:
            print_generated(self.console, rel)
        else:
            print_skipped(self.console, rel)
        return [(rel, status)]

    def _generate_ci(
        self, cfg: LaunchKitConfig, root: Path
    ) -> list[tuple[str, str]]:
        results: list[tuple[str, str]] = []
        provider = cfg.ci.provider

        if provider == CIProvider.GITHUB:
            content = generate_github_actions(cfg)
            filepath = root / ".github" / "workflows" / "ci.yml"
        elif provider == CIProvider.GITLAB:
            content = generate_gitlab_ci(cfg)
            filepath = root / ".gitlab-ci.yml"
        else:
            print_warning(self.console, f"CI provider '{provider.value}' is not yet supported")
            return []

        rel = str(filepath.relative_to(root))
        wrote = safe_write(filepath, content, dry_run=self.dry_run)
        status = ("dry-run" if self.dry_run else "generated") if wrote else "skipped"
        if wrote:
            print_generated(self.console, rel)
        else:
            print_skipped(self.console, rel)
        results.append((rel, status))

        return results

    def _generate_k8s(
        self, cfg: LaunchKitConfig, root: Path, k8s_prefix: str
    ) -> list[tuple[str, str]]:
        target = cfg.deploy.target
        if target not in (DeployTarget.KUBERNETES, DeployTarget.BOTH):
            if self.only == "k8s":
                print_info(self.console, "deploy.target is not 'kubernetes' or 'both' — generating anyway")
            elif self.only is None:
                return []

        results: list[tuple[str, str]] = []

        for name, service in cfg.services.items():
            # Deployment
            dep_content = generate_deployment(name, service, cfg)
            dep_path = root / k8s_prefix / name / "deployment.yaml"
            results.append(self._write_file(dep_path, dep_content, root))

            # Service (web only)
            if service.type == ServiceType.WEB and service.port:
                svc_content = generate_service(name, service, cfg)
                svc_path = root / k8s_prefix / name / "service.yaml"
                results.append(self._write_file(svc_path, svc_content, root))

            # HPA
            if service.scale.max > 1:
                hpa_content = generate_hpa(name, service, cfg)
                hpa_path = root / k8s_prefix / name / "hpa.yaml"
                results.append(self._write_file(hpa_path, hpa_content, root))

            # Secrets hint
            secrets = generate_secrets_hint(name, service, cfg, root)
            if secrets:
                sec_path = root / k8s_prefix / name / "secrets-hint.yaml"
                results.append(self._write_file(sec_path, secrets, root))

        # Ingress (one per project if enabled)
        if cfg.deploy.ingress.enabled:
            ing_content = generate_ingress(cfg)
            ing_path = root / k8s_prefix / "ingress.yaml"
            results.append(self._write_file(ing_path, ing_content, root))

        return results

    def _generate_nginx(
        self, cfg: LaunchKitConfig, root: Path, k8s_prefix: str
    ) -> list[tuple[str, str]]:
        if not cfg.deploy.nginx.enabled:
            return []

        web_count = sum(1 for s in cfg.services.values() if s.type == ServiceType.WEB)
        if web_count == 0:
            return []

        results: list[tuple[str, str]] = []

        # Generate nginx.conf
        nginx_conf = generate_nginx_conf(cfg)
        if nginx_conf:
            conf_path = root / "nginx" / "nginx.conf"
            results.append(self._write_file(conf_path, nginx_conf, root))

        # Generate K8s resources for nginx
        target = cfg.deploy.target
        if target in (DeployTarget.KUBERNETES, DeployTarget.BOTH):
            k8s_content = generate_nginx_k8s(cfg)
            k8s_path = root / k8s_prefix / "nginx" / "nginx.yaml"
            results.append(self._write_file(k8s_path, k8s_content, root))

        return results

    def _write_file(
        self, filepath: Path, content: str, root: Path
    ) -> tuple[str, str]:
        rel = str(filepath.relative_to(root))
        wrote = safe_write(filepath, content, dry_run=self.dry_run)
        status = ("dry-run" if self.dry_run else "generated") if wrote else "skipped"
        if wrote:
            print_generated(self.console, rel)
        else:
            print_skipped(self.console, rel)
        return (rel, status)


# ── Dockerfile builder ───────────────────────────────────────────────────────


def _build_dockerfile(
    name: str, service: ServiceConfig, service_dir: Path | None = None
) -> str:
    lang = service.lang.value
    if lang == "python":
        return generate_python_dockerfile(name, service, service_dir)
    elif lang == "node":
        return generate_node_dockerfile(name, service)
    elif lang == "go":
        return generate_go_dockerfile(name, service)
    elif lang == "java":
        return generate_java_dockerfile(name, service)
    elif lang == "rust":
        return generate_rust_dockerfile(name, service)
    elif lang == "ruby":
        return generate_ruby_dockerfile(name, service)
    elif lang == "php":
        return generate_php_dockerfile(name, service)
    elif lang == "dotnet":
        return generate_dotnet_dockerfile(name, service)
    else:
        raise ValueError(f"Unsupported language: {lang}")
