"""Tests for eject command."""

from __future__ import annotations

from pathlib import Path

import pytest
import yaml
from rich.console import Console

from launchkit.core.eject import run_eject, _find_managed_files, _clean_file


@pytest.fixture
def quiet_console() -> Console:
    return Console(quiet=True)


@pytest.fixture
def generated_project(tmp_path: Path) -> Path:
    """Create a project with LaunchKit-generated files."""
    # launchkit.yaml
    config = {"version": "1", "project": {"name": "test", "registry": "test"}, "services": {}}
    (tmp_path / "launchkit.yaml").write_text(yaml.dump(config))

    # Generated Dockerfile
    (tmp_path / "Dockerfile").write_text(
        "# Generated by LaunchKit — https://github.com/yourname/launchkit\n"
        "# Do not edit manually — run `launchkit generate` to regenerate\n"
        "FROM python:3.12\nCOPY . .\n"
    )

    # Generated K8s manifest
    k8s = tmp_path / "k8s" / "api"
    k8s.mkdir(parents=True)
    (k8s / "deployment.yaml").write_text(
        "# Generated by LaunchKit\n"
        "apiVersion: apps/v1\n"
        "kind: Deployment\n"
        "metadata:\n"
        "  name: api\n"
        "  labels:\n"
        "    app: api\n"
        "    managed-by: launchkit\n"
        "  annotations:\n"
        "    launchkit.dev/resource-profile: standard-api\n"
    )

    return tmp_path


class TestFindManagedFiles:
    def test_finds_managed_files(self, generated_project: Path) -> None:
        files = _find_managed_files(generated_project)
        assert len(files) >= 2
        names = [f.name for f in files]
        assert "Dockerfile" in names
        assert "deployment.yaml" in names

    def test_ignores_launchkit_yaml(self, generated_project: Path) -> None:
        files = _find_managed_files(generated_project)
        names = [f.name for f in files]
        assert "launchkit.yaml" not in names


class TestCleanFile:
    def test_strips_header(self, tmp_path: Path) -> None:
        f = tmp_path / "test.txt"
        f.write_text("# Generated by LaunchKit — test\nFROM python:3.12\n")
        changed = _clean_file(f)
        assert changed is True
        assert "Generated by LaunchKit" not in f.read_text()
        assert "FROM python:3.12" in f.read_text()

    def test_strips_labels(self, tmp_path: Path) -> None:
        f = tmp_path / "test.yaml"
        f.write_text("labels:\n  app: api\n  managed-by: launchkit\n")
        changed = _clean_file(f)
        assert changed is True
        assert "managed-by" not in f.read_text()

    def test_no_change_clean_file(self, tmp_path: Path) -> None:
        f = tmp_path / "clean.txt"
        f.write_text("FROM python:3.12\nCOPY . .\n")
        changed = _clean_file(f)
        assert changed is False


class TestRunEject:
    def test_eject_with_yes(self, generated_project: Path, quiet_console: Console) -> None:
        assert (generated_project / "launchkit.yaml").exists()
        run_eject(str(generated_project), yes=True, console=quiet_console)
        assert not (generated_project / "launchkit.yaml").exists()
        # Files should remain but be clean
        assert (generated_project / "Dockerfile").exists()
        content = (generated_project / "Dockerfile").read_text()
        assert "Generated by LaunchKit" not in content

    def test_eject_no_config(self, tmp_path: Path, quiet_console: Console) -> None:
        run_eject(str(tmp_path), yes=True, console=quiet_console)
        # Should not crash
